# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/reference/configuration-reference
# This is the first config in circleci
version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@3.0.1

jobs:
  build-and-push:
    environment:
      - DOCKER_IMAGE: nhatky1601/learning_assistant
      - DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: ${DOCKER_IMAGE}
          tag: ${DOCKER_TAG}
      - docker/push:
          digest_path: /tmp/digest.txt
          image: ${DOCKER_IMAGE}
          tag: ${DOCKER_TAG}
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  buil-deploy:
    jobs:
      - node/test
      - build-and-push:
        requires:
          - node/test
        filters:
          branches:
            only:
              - main